### PR TITLE
Protected Seas layers

### PR DESCRIPTION
**Pull request by nerik**
Currently with levels 3, 4 and 5.

screenshot 2019-02-13 at 17 05 03

Here's what's needed in the default workspace:

```
{
          "label": "Protected Seas: most restrictive",
          "title": "Protected Seas: most restrictive",
          "description": "",
          "visible": true,
          "color": "#F84F40",
          "type": "CartoDBAnimation",
          "opacity": 1,
          "id": "protectedseas_level5",
          "added": true,
          "library": true
        },
        {
          "label": "Protected Seas: heavily restrictive",
          "title": "Protected Seas: heavily restrictive",
          "description": "",
          "visible": true,
          "color": "#fca26f",
          "type": "CartoDBAnimation",
          "opacity": 1,
          "id": "protectedseas_level4",
          "added": true,
          "library": true
        },
        {
          "label": "Protected Seas: moderately restrictive",
          "title": "Protected Seas: moderately restrictive",
          "description": "",
          "visible": true,
          "color": "#FBFF8B",
          "type": "CartoDBAnimation",
          "opacity": 1,
          "id": "protectedseas_level3",
          "added": true,
          "library": true
        },
```

### CODE REVIEW

**Comment by enriquetuya** [comment]
@nerik Back then you implemented the ability of adding layers from carto directly in the workspace. Can't this be achieved in this way without modifying the styles.json? I'm asking because in terms of iteration that would be much faster.

**Comment by nerik** [comment]
@enriquetuya Yes, layers could be defined as such in the workspace:

```
{
          "label": "Protected Seas: most restrictive",
          "title": "Protected Seas: most restrictive",
          "description": "",
          "visible": true,
          "color": "#F84F40",
          "type": "CartoDBAnimation",
          "opacity": 1,
          "id": "protectedseas_level5",
          "added": true,
          "library": true,
          "gl": {
            "source": {
              "metadata": {
                "gfw:carto-sql": "SELECT *, 'most restrictive' AS level, concat('https://mpa.protectedseas.net/index.php?z=6&pin&q=',site_id) AS details FROM protectedseas_level5_mostrestrictive",
                "gfw:popups": [
                  { "id": "site_name" },
                  { "id": "level" },
                  { "id": "country" },
                  { "id": "season" },
                  { "id": "details", "isLink": true }
                ]
              },
              "type": "vector"
            },
            "layers": [
              {
                "id": "protectedseas_level5",
                "type": "fill",
                "source": "protectedseas_level5",
                "source-layer": "protectedseas_level5",
                "layout": { 
                 "visibility": "none"
                },
                "interactive": true
              },
              {
                "id": "protectedseas_level5-labels",
                "type": "symbol",
                "source": "protectedseas_level5",
                "source-layer": "protectedseas_level5",
                "layout": {
                  "visibility": "none",
                  "text-field": "{site_name}",
                  "text-font": [
                    "Roboto Mono Light"
                  ],
                  "text-size": 10
                }
              },
            ]
          }
        }
```

I can remove the `style.json` edits from the PR, although I'd favor storing this data in this file in the long term if we plan to keep the layers visible in the default workspace.

**Comment by enriquetuya** [comment]
@nerik if that is the case, since we don't know how much iterations we will need to get this straight until public let's use the workspace approach.
In your PR there are some code outsited the styles.json, let's get that merged and the rest let's generate a workspace using the default workspace as a base.

Could you please work on that?
* [ ] Remove the styles.json changes from this pr, only leaving the styles changes and the Static pop-up change.
* [ ] Create a workspace with the embeded layers.

**Comment by nerik** [comment]
You got it. 
Workspace is here: https://globalfishingwatch.org/map/?workspace=udw-v2-9c8a0021-486b-462b-a5d1-a084dccf5ed5

**Comment by enriquetuya** [comment]
Renamed to: https://globalfishingwatch.org/map/workspace/protected-seas-v1

**Pull request merged**
